version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run:
          name: Saludos
          command: echo Hola Mundo!
      - ruby/bundle-install
       - run:
          name: Imprime la fecha
          command: Date
